[project]
name = "kl"
version = "0.1.0"
description = ""
authors = [
    {name = "mssp", email = "mssp@mssp.com"},
]
dependencies = [
    "starknet-py>=0.20.0",
    "asyncio>=3.4.3",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

