const WOOD_BUILDING_COUNT: u64 = 4;
const BRICK_BUILDING_COUNT: u64 = 4;
const STEEL_BUILDING_COUNT: u64 = 4;
const FOOD_BUILDING_COUNT:u64 = 6;
const CITY_HALL_COUNT:u64 = 1;
const WAREHOUSE_COUNT:u64 = 1;
const BARN_COUNT:u64 = 1;

const WOOD_BUILDING_START_INDEX: u64 = 0;
const BRICK_BUILDING_START_INDEX: u64 = 4;
const STEEL_BUILDING_START_INDEX: u64 = 8;
const FOOD_BUILDING_START_INDEX: u64 = 12;

const BASE_GROW_RATE: u64 = 4;
// const WOOD_BASE_GROW_RATE:u64 = 10;
// const BRICK_BASE_GROW_RATE:u64 = 10;
// const STEEL_BASE_GROW_RATE:u64 = 10;
// const FOOD_BASE_GROW_RATE:u64 = 10;

const INITIAL_MAX_STORAGE: u64 = 1000;

const WAITING_UPGRADING_COUNT: u64 = 5;
const UNDER_TRAINING_COUNT: u64 = 20;

const OUTER_CITY_BUILDING_AMOUNT:u64 = 18;
const INNER_CITY_BUILDING_AMOUNT: u64 = 21;

const CONFIG_ID: u64 = 1;
