name: CI

on:
  push:
  pull_request:
env:
  DEPLOY_RPC_URL: https://katana1.0xmssp.xyz
  TARGET_NAME: mssp

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: curl -L https://install.dojoengine.org | bash
      - run: /home/runner/.config/.dojo/bin/dojoup
      - run: echo $PATH
      - run: cp /home/runner/.config/.dojo/bin/sozo /usr/local/bin/sozo
      - run: sozo --profile ${{ env.TARGET_NAME }} build
      - run: sozo --profile ${{ env.TARGET_NAME }} test
      - name: stop torii service, restart katana
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.WILL }}
          username: ${{ secrets.USER }}
          script: systemctl stop torii.service; systemctl stop katana-genblock.service;rm -rf /var/katana; systemctl restart katana.service
      - run: sozo --profile ${{ env.TARGET_NAME }} migrate apply
      - uses: actions/upload-artifact@v4
        with:
          name: manifest.json
          path: manifest/${{ env.TARGET_NAME }}/manifest.json
      - run: bash scripts/default_auth.sh
      - name: start torii service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.WILL }}
          username: ${{ secrets.USER }}
          script: systemctl start torii.service; systemctl start katana-genblock.service
      - name: set merkle data
        run: bash scripts/set_testnet_merkle.sh
      - name: try spawn
        run: bash scripts/test/spawn.sh
